### ISSUE TITLE
docker not enough values to unpack

### ISSUE THREAD

**Issue by nonomal** [malaohu/MobaXterm-GenKey#1]
* Serving Flask app "app" (lazy loading)

 * Environment: production

   WARNING: This is a development server. Do not use it in a production deployment.

   Use a production WSGI server instead.

 * Debug mode: on

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

 * Restarting with stat

 * Debugger is active!

 * Debugger PIN: 160-472-655

192.168.20.11 - - [29/Mar/2021 23:27:30] "GET / HTTP/1.1" 500 -

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise

    raise value

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise

    raise value

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/usr/src/app/app.py", line 129, in get

    lc = get_lc()

  File "/usr/src/app/app.py", line 110, in get_lc

    MajorVersion, MinorVersion = version.split('.')[0:2]

ValueError: not enough values to unpack (expected 2, got 1)

192.168.20.11 - - [29/Mar/2021 23:27:30] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -

192.168.20.11 - - [29/Mar/2021 23:27:30] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -

192.168.20.11 - - [29/Mar/2021 23:27:30] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -

192.168.20.11 - - [29/Mar/2021 23:27:31] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -

192.168.20.11 - - [29/Mar/2021 23:27:31] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

192.168.20.11 - - [29/Mar/2021 23:27:31] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by malaohu** [comment]
fix bug

https://github.com/malaohu/MobaXterm-GenKey/commit/4acb240b73bd7d9417fb2373ca5bb6e81e29c762
